version: '3'
services:

services:

 postgres:
  container_name: postgres_guacamole_compose
  environment:
   PGDATA: /var/lib/postgresql/data/guacamole
   POSTGRES_DB: guacamole_db
   POSTGRES_PASSWORD: ChooseYourOwnPasswordHere1234
   POSTGRES_USER: guacamole_user
  image: postgres
  restart: always
  volumes:
   - ./init:/docker-entrypoint-initdb.d:ro
   - ./data:/var/lib/postgresql/data:rw
 guacd:
  container_name: guacd_compose
  image: guacamole/guacd
  restart: always
  volumes:
   - ./drive:/drive:rw
   - ./record:/record:rw
 guacamole:
  container_name: guacamole_compose
  depends_on:
   - guacd
   - postgres
  environment:
   GUACD_HOSTNAME: guacd
   POSTGRES_DATABASE: guacamole_db
   POSTGRES_HOSTNAME: postgres
   POSTGRES_PASSWORD: ChooseYourOwnPasswordHere1234
   POSTGRES_USER: guacamole_user
  image: guacamole/guacamole
  links:
   - guacd
  ports:
   - 8080:8080/tcp
  restart: always

 amethyst-examples:
  image: marcelmaatkamp/amethyst/examples:latest
  entrypoint: cargo
  command: ${COMMAND}
  build:
   context: .
  volumes:
   - target:/amethyst/target
   - assets_db:/amethyst/.assets_db
  environment:
   COMMAND: ${COMMAND:-"run -p hello_world"}

volumes:
 target:
 assets_db:
